### ISSUE TITLE
Running Fireplace with "fireplace.yaml" in ~/.config panics

### ISSUE THREAD

**Issue by Timidger** [Drakulix/fireplace#16]
When trying to run Fireplace with the default configuration at `~/.config/fireplace.yaml` I get the following panic:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MoreThanOneDocument', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:868
stack backtrace:
   1:     0x564985923c7a - std::sys::imp::backtrace::tracing::imp::write::h55f5b644254d8997
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x564985923101 - std::panicking::default_hook::{{closure}}::h5341ac454af9dec5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x564985922267 - std::panicking::rust_panic_with_hook::h0c50036d8a952120
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:545
   4:     0x564985921dc1 - std::panicking::begin_panic::h549a5cdf22ed84a1
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:507
   5:     0x564985921d39 - std::panicking::begin_panic_fmt::h1e2376a100034ec9
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:491
   6:     0x564985932d16 - core::panicking::panic_fmt::hfaaf47fca562bd04
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:467
   7:     0x5649857cf2ed - core::result::unwrap_failed::hc6c740f9ff9a57a7
   8:     0x5649857e77a3 - fireplace::main::h92784384c58e10a0
   9:     0x5649857ef351 - main
  10:     0x7f38776e057f - __libc_start_main
  11:     0x56498573dad8 - _start
  12:                0x0 - <unknown>
```

It other wise runs fine if I don't put the configuration file there.

**Comment by Drakulix** [comment]
Thanks for that report. That is actually really bad for a first user experience, so I am going to work on this asap. I currently assume the `---` lines are causing this problem, but will debug this further tomorrow and upload a new example configuration once this is resolved.
