### ISSUE TITLE
3.1.1 - Default configuration not working

### ISSUE THREAD

**Issue by Doaxan** [Drakulix/fireplace#38]
Im trying to use https://github.com/Drakulix/fireplace/releases/tag/v3.1.1/fireplace , but get this error:
```
❯ env RUST_BACKTRACE=full fireplace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: EndOfStream', /checkout/src/libcore/result.rs:860
stack backtrace:
   0:     0x55fbcc2ed883 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h3c67687ba454b78b
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55fbcc2e9bc9 - std::panicking::default_hook::{{closure}}::h07b8ee04b5734d1a
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   2:     0x55fbcc2e8cd6 - std::panicking::rust_panic_with_hook::hd0067971b6d1240e
                               at /checkout/src/libstd/panicking.rs:371
                               at /checkout/src/libstd/panicking.rs:549
   3:     0x55fbcc2e87e1 - std::panicking::begin_panic::h1fd1f10a3de8f902
                               at /checkout/src/libstd/panicking.rs:511
   4:     0x55fbcc2e8759 - std::panicking::begin_panic_fmt::haa043917b5d6f21b
                               at /checkout/src/libstd/panicking.rs:495
   5:     0x55fbcc2fc1d6 - core::panicking::panic_fmt::he9c7f335d160b59d
                               at /checkout/src/libstd/panicking.rs:471
   6:     0x55fbcc181802 - core::result::unwrap_failed::h45dce2a959def761
   7:     0x55fbcc19bcd3 - fireplace::main::h501166b0e261f422
   8:     0x55fbcc1a2bb1 - main
   9:     0x7ffb71791400 - __libc_start_main
  10:     0x55fbcc0c9a18 - _start
  11:                0x0 - <unknown>
```

**Comment by Drakulix** [comment]
looks like a broken config file, can you post yours?

**Comment by Doaxan** [comment]
Forgot about config file, thanks! :)
It would be nice to give informative output something like "non-exist config file".

**Comment by Drakulix** [comment]
Oh you simply did not have one? That is supposed to work with a default configuration and definitely a bug, most likely introduced by a028080dac9ca0e6e5904c22b03e4579501ff88e. I will fix this, thanks!
